apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-rules
  namespace: monitoring
spec:
  groups:
    - name: linux Disk Alerts
      rules:
        - alert: DiskSpaceUsage
          expr: 100 - (node_filesystem_avail_bytes{fstype=~"ext.?|xfs",mountpoint!~".+docker.*|.+kubelet.*"} / node_filesystem_size_bytes{fstype=~"ext.?|xfs",mountpoint!~".+docker.*|.+kubelet.*"} * 100) > 90
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "{{$labels.instance}} Partition utilization too high"
            description: "{{$labels.instance }} Partition usage greater than 90%(Currently used:{{$value}}%)"
        - alert: DiskSIOPerformance
          expr: 100-(avg(irate(node_disk_io_time_seconds_total[1m])) by(instance)* 100) < 60
          for: 1m
          labels:
            severity: high
          annotations:
            summary: "{{$labels.instance}} The IO utilization rate of incoming disk is too high"
            description: "{{$labels.instance }} The incoming disk IO is greater than 60%(Currently used:{{$value}})"
    - name: linux Cpu
      rules:
        - alert: CpuUsage
          expr: 100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)* 100) > 60
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "{{$labels.instance}} CPU The utilization rate is too high"
            description: "{{$labels.instance }} CPU Use greater than 60%(Currently used:{{$value}}%)"
    - name: linux Memory
      rules:
        - alert:  MemoryLow
          expr: (1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes))) * 100 > 90
          for: 1m
          labels:
            severity: high
          annotations:
            summary: "{{$labels.instance}} High memory usage"
            description: '{{$labels.instance }} Memory greater than 90%(Currently used:{{$value}}%)'
    - name: Instance Down
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Instance {{ $labels.instance }} down"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minute."